# rust4failures — the local mirror of .github/workflows/CI.yaml.
#
# This repository is generated by the book. The workflow is the thing that
# judges the code, so every target below is one of its jobs, run with the same
# flags. If a target here is green and GitHub is red, one of the two files is
# lying — and that is a bug worth chasing.
#
# `make ci` runs the jobs the way the workflow runs them, on this machine, with
# whatever toolchain `rustup` gives you. `make act` runs the workflow itself in
# a container, which is slower but is the real thing.

.PHONY: default help test clippy fmt fmt-fix doc ci act clean

# The workflow sets this once, at the top, so it applies to every job.
# Warnings are errors. That is the whole point of the book.
export RUSTFLAGS := -Dwarnings

# `act` on Apple silicon needs to be told to run the amd64 runner image.
# Override on the command line if you know better: make act ACT_FLAGS=
ACT_FLAGS ?= --container-architecture linux/amd64

default: ci

help:
	@echo "Available targets:"
	@echo "  make (default)  - Run every CI job locally (same as 'make ci')"
	@echo "  make ci         - test, clippy, fmt, doc — the four jobs in CI.yaml"
	@echo "  make test       - cargo test --all"
	@echo "  make clippy     - cargo clippy, pedantic, warnings denied"
	@echo "  make fmt        - Check formatting. Fails if anything is unformatted."
	@echo "  make fmt-fix    - Actually reformat the code"
	@echo "  make doc        - Build the docs. A doc warning is an error."
	@echo "  make act        - Run the real workflow in Docker, using 'act'"
	@echo "  make clean      - cargo clean"

# --- the four jobs, one target each ----------------------------------------
# Each recipe is copied from the matching `run:` line in CI.yaml. Keep them
# copied. A target that "improves" on the workflow stops being a mirror of it.

# CI.yaml: job `test`. The workflow runs this on a matrix of toolchains; you
# have one. `make act` is what covers the matrix.
test:
	cargo test --all

# CI.yaml: job `clippy`.
clippy:
	cargo clippy -- -Dclippy::all -Dclippy::pedantic

# CI.yaml: job `fmt`. `--check` reports and fails; it changes nothing.
fmt:
	cargo fmt --all -- --check

# Not a job. The fix for the job above.
fmt-fix:
	cargo fmt --all

# CI.yaml: job `doc`. RUSTDOCFLAGS is set on this job alone in the workflow,
# so it is set on this target alone here.
doc:
	RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --document-private-items

# Everything, in the order a reader wants to hear about it: does it build and
# pass, is it clean, is it tidy, is it documented.
ci: test clippy fmt doc

# --- the real workflow ------------------------------------------------------
# `act` (https://github.com/nektos/act) reads .github/workflows/ and runs the
# jobs in Docker containers. It needs two things, and it is worth saying which
# one is missing rather than dying on an unreadable error.
act:
	@missing=""; \
	if ! command -v act >/dev/null 2>&1; then \
		missing="$$missing act"; \
	fi; \
	if ! docker info >/dev/null 2>&1; then \
		missing="$$missing docker"; \
	fi; \
	if [ -n "$$missing" ]; then \
		echo "Cannot run the workflow locally. Missing:$$missing"; \
		echo ""; \
		case "$$missing" in *act*) \
			echo "  act     - brew install act"; \
			echo "            or see https://github.com/nektos/act#installation"; \
		esac; \
		case "$$missing" in *docker*) \
			echo "  docker  - install Docker Desktop, then start it."; \
			echo "            'docker info' has to succeed before act will run."; \
		esac; \
		echo ""; \
		echo "Until then, 'make ci' runs the same commands without a container."; \
		exit 1; \
	fi; \
	echo "Running .github/workflows/CI.yaml with act. The first run downloads a"; \
	echo "large runner image; later runs are much faster."; \
	act $(ACT_FLAGS)

clean:
	cargo clean
